# Generated by Django 5.1.6 on 2025-03-13 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='heure_cumulee',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
