# Generated by Django 5.1.6 on 2025-03-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0004_alter_cours_heure_cumulee_alter_cours_heure_restante'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='volume_horaire_effectue',
            field=models.FloatField(default=0),
        ),
    ]
