# Generated by Django 5.1.6 on 2025-03-13 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0005_enseignant_volume_horaire_effectue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='heure_restante',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='volume_horaire_effectue',
        ),
        migrations.CreateModel(
            name='SuiviVolumeHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_horaire_total', models.FloatField()),
                ('heures_effectuees', models.FloatField(default=0)),
                ('heures_restantes', models.FloatField(default=0)),
                ('statut', models.CharField(default='En cours', max_length=20)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='emargement.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='emargement.matiere')),
            ],
        ),
    ]
