# Generated by Django 5.1.6 on 2025-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0006_remove_cours_heure_restante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivivolumehoraire',
            name='heures_effectuees',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='suivivolumehoraire',
            name='heures_restantes',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='suivivolumehoraire',
            name='volume_horaire_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
