# Generated by Django 5.1.7 on 2025-03-24 17:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0007_alter_suivivolumehoraire_heures_effectuees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='heure_cumulee',
        ),
        migrations.RemoveField(
            model_name='suivivolumehoraire',
            name='heures_effectuees',
        ),
        migrations.RemoveField(
            model_name='suivivolumehoraire',
            name='heures_restantes',
        ),
        migrations.RemoveField(
            model_name='suivivolumehoraire',
            name='volume_horaire_total',
        ),
        migrations.AddField(
            model_name='suivivolumehoraire',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='suivivolumehoraire',
            name='heures_realisees',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='suivivolumehoraire',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_volume_horaire', to='emargement.enseignant'),
        ),
        migrations.AlterField(
            model_name='suivivolumehoraire',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi_volume_horaire', to='emargement.matiere'),
        ),
        migrations.AlterField(
            model_name='suivivolumehoraire',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=50),
        ),
        migrations.CreateModel(
            name='EmargementApresCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emargement', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emargements_apres', to='emargement.cours')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='EmargementAvantCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emargement', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emargements_avant', to='emargement.cours')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='HeuresCumulees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heures_total', models.FloatField(default=0)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heures_cumulees', to='emargement.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heures_cumulees', to='emargement.matiere')),
            ],
        ),
        migrations.DeleteModel(
            name='Devoir',
        ),
    ]
