# Generated by Django 5.1.7 on 2025-03-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0008_remove_cours_heure_cumulee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emargementavantcours',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='emargementaprescours',
            name='cours',
        ),
        migrations.RemoveField(
            model_name='emargementaprescours',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='emargementavantcours',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='heurescumulees',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='heurescumulees',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='suivivolumehoraire',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='suivivolumehoraire',
            name='matiere',
        ),
        migrations.DeleteModel(
            name='Cours',
        ),
        migrations.DeleteModel(
            name='EmargementApresCours',
        ),
        migrations.DeleteModel(
            name='EmargementAvantCours',
        ),
        migrations.DeleteModel(
            name='HeuresCumulees',
        ),
        migrations.DeleteModel(
            name='SuiviVolumeHoraire',
        ),
    ]
