# Generated by Django 5.1.7 on 2025-03-24 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0009_remove_emargementavantcours_cours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='Devoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=100)),
                ('date_devoir', models.DateField()),
                ('statut', models.CharField(choices=[('Programmé', 'Programmé'), ('Exécuté', 'Exécuté')], max_length=10)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Emargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=100)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('type_emargement', models.CharField(choices=[('avant', 'Avant le cours'), ('apres', 'Après le cours')], max_length=5)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviVolumeHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_realisees', models.FloatField(default=0)),
                ('heures_restantes', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('Terminé', 'Terminé'), ('En Cours', 'En Cours')], max_length=10)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.matiere')),
            ],
        ),
    ]
