# Generated by Django 5.1.7 on 2025-03-27 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0010_alter_enseignant_email_devoir_emargement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devoir',
            old_name='filiere',
            new_name='classe',
        ),
        migrations.RenameField(
            model_name='devoir',
            old_name='date_devoir',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='suivivolumehoraire',
            old_name='heures_realisees',
            new_name='volume_horaire_restant',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='libelle',
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='volume_horaire',
        ),
        migrations.RemoveField(
            model_name='suivivolumehoraire',
            name='heures_restantes',
        ),
        migrations.RemoveField(
            model_name='suivivolumehoraire',
            name='statut',
        ),
        migrations.AddField(
            model_name='enseignant',
            name='contact',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='matiere',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AddField(
            model_name='matiere',
            name='volume_horaire_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='suivivolumehoraire',
            name='classe',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='grade',
            field=models.CharField(default='Non spécifié', max_length=50),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(default='MATRICULE_INCONNU', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='prenom',
            field=models.CharField(default='Inconnu', max_length=100),
        ),
        migrations.CreateModel(
            name='EmargementAvantCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.matiere')),
            ],
            options={
                'unique_together': {('enseignant', 'matiere', 'classe', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EmargementApresCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_fin', models.TimeField()),
                ('emargement_avant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emargement.emargementavantcours')),
            ],
        ),
        migrations.DeleteModel(
            name='Emargement',
        ),
    ]
