# Generated by Django 5.1.7 on 2025-03-28 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0011_rename_filiere_devoir_classe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suivivolumehoraire',
            name='classe',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Enseignement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100)),
                ('horaire', models.CharField(max_length=100)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emargement.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matieres',
            field=models.ManyToManyField(through='emargement.Enseignement', to='emargement.matiere'),
        ),
    ]
