# Generated by Django 5.1.7 on 2025-03-28 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emargement', '0012_alter_suivivolumehoraire_classe_enseignement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='devoir',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='enseignement',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='suivivolumehoraire',
            name='classe',
        ),
        migrations.AlterUniqueTogether(
            name='emargementavantcours',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='devoir',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emargement.filiere'),
        ),
        migrations.AddField(
            model_name='emargementavantcours',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emargement.filiere'),
        ),
        migrations.AddField(
            model_name='enseignement',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emargement.filiere'),
        ),
        migrations.AddField(
            model_name='suivivolumehoraire',
            name='filiere',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='emargement.filiere'),
        ),
        migrations.AlterUniqueTogether(
            name='emargementavantcours',
            unique_together={('enseignant', 'matiere', 'filiere', 'date')},
        ),
        migrations.RemoveField(
            model_name='emargementavantcours',
            name='classe',
        ),
    ]
